name: Build and Test (Galactic)
on:
  push:
    branches: [ galactic ]
  pull_request:
    branches: [ galactic ]
jobs:
  build-and-test:
    runs-on: ubuntu-latest
    container:
      image: rostooling/setup-ros-docker:ubuntu-focal-ros-galactic-desktop-latest
    steps:
      - name: Setup git-lfs
        run: apt-get update && apt-get install -y git-lfs && rm -rf /var/lib/apt/lists/*
      - name: Check out
        uses: actions/checkout@v2.3.4
        with:
          fetch-depth: 0
      - name: Build rmoss_daheng_driver
        uses: ros-tooling/action-ros-ci@v0.2
        with:
          target-ros2-distro: galactic
          vcs-repo-file-url: "${{ github.workspace }}/dependency.repos"
          skip-tests: true
      - name: Test rmoss_daheng_driver
        run: |
          source /opt/ros/galactic/setup.sh
          cd ros_ws
          colcon test --packages-select rmoss_daheng_driver --event-handlers console_cohesion+ --return-code-on-test-failure
