name: Build and Test (Humble)
on:
  push:
    branches: [ humble ]
  pull_request:
    branches: [ humble ]
  schedule:
    - cron: '0 21 * * *'
jobs:
  build-and-test:
    runs-on: ubuntu-latest
    container:
      image: rostooling/setup-ros-docker:ubuntu-jammy-ros-humble-desktop-latest
    steps:
      - name: Setup git-lfs
        run: apt-get update && apt-get install -y git-lfs && rm -rf /var/lib/apt/lists/*
      - name: Check out
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          lfs: true
      - name: Build rmoss_daheng_driver
        uses: ros-tooling/action-ros-ci@v0.3
        with:
          package-name: rmoss_daheng_driver
          target-ros2-distro: humble
          vcs-repo-file-url: "${{ github.workspace }}/dependency.repos"
          skip-tests: true
      - name: Test rmoss_daheng_driver
        run: |
          . /opt/ros/humble/setup.sh
          cd ros_ws
          colcon test --packages-select rmoss_daheng_driver --event-handlers console_cohesion+ --return-code-on-test-failure
